---
title: "Introduction to SynergyScreen"
author: "Yury V. Bukhman"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction to SynergyScreen}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script> 

The purpose of SynergyScreen package is to facilitate design and analysis of medium-throughput screens of collections of compounds for pairwise  interactions using microtiter plates.

## Background

### Synergy experiments
Compounds that are toxic to certain types of living cells are of great importance in a number of fields.  Examples include cancer drugs, agricultural pest control agents and bi-products of biomass pre-processing and hydrolysis in biofuel production systems.  Toxicity of such compounds is often assayed by measuring inhibition of growth in cell cultures.  In practice, cells are often exposed to two or more toxic compounds.  This can be deliberate, as in cancer drug cocktails, or unintentional, as in hydrolyzates used to produce biofuels.  In such mixtures, compounds often interact to enhance or suppress each other's effects.  In order to assess and quantify these interactions, researchers compare inhibitory effects of individual compounds to those of their combinations.  

A common way to investigate the inhibitory effect of a toxic agent, e.g. a chemical compound or cocktail, is to build and analyze a dose-response curve.  Such curves are generated by exposing a cell culture to increasing doses of the agent and monitoring growth, e.g. by measuring optical density (*OD*).  For example, a following dose-response experiment can be set up in a microtiter plate. Plate wells contain growth media.  A series of doses of a toxic agent in increasing concentrations is added to some wells, while a buffer is added to others.  The wells are inoculated with a cell culture.  After a period of time, *OD* is measured in each well.  The wells that contain no toxic agent will have the highest *OD*: they are **untreated controls**.  The wells that contain the toxin will have lower *OD*.  A plot of *OD* values vs. the dose of the toxin is referred to as a **dose-response curve**.  An example dose-response curve is shown in **[Figure 1]**.

An efficient way to assess interaction of two compounds is to perform a "single ray" experiment.  In such an experiment, an investigator measures dose-response curves of the two individual compounds and of their mixture in a fixed proportion.  Once the three resulting dose-response curves are analyzed, it is possible to assess interaction by analyzing an isobole plot.  In an isobole plot, two axes represent the doses of the two compounds.  The doses of the mixture lie along a straight line, $y = kx$, where $k = y/x$ is the ratio of the two compounds in the mixture.  An isobole is a line that connects doses of the two compounds and the mixture that result in equal response.  A widely used way to assess interactions is to assume that, when none exists, the isobole is a straight line **[ref Berenbaum]**.  In particular, this will be the case when the two compounds are the same, i.e. mixing non-interacting compounds is like mixing a compound with itself.  The isoboles are concave-up in the presense of synergy, i.e. it takes less of the mixture to produce the same inhibitory effect as compared to the no-interaction scenario.  The isoboles are concave-down in the presense of antagonism.  Examples of no-interaction, synergy, and antagonism are shown in **[Figure 2]**.

### Mathematical modeling of growth curves 
#### Control response
When synergy experiments are designed, they must include several measurements of response (e.g. *OD*) of untreated controls.  Controls are cell cultures that are allowed to grow in the absense of toxins.  The models of dose-response curves used by SynergyScreen rely heavily on a fixed known control response value.  This value is obtained by averaging control responses, i.e. from all wells designated as controls in a 96-well plate.

#### Non-linear regression
Dose-response curves are often modelled using the median effect equation **[ref Chou and Talalay]**:
$$
\begin{align}
R = \frac{R_0}{1+\left(\frac{D}{D_{50}}\right)^m}
\end{align}
$$
where $R$ is response (e.g. *OD*), $R_0$ is control response, $D$ is the dose of the toxin and $D_{50}$ is the dose that causes 50% inhibition of growth (also known as $IC_{50}$).  The original meaning of $m$ was the number of inhibitor binding sites on an enzyme, as this equation was first developed in the context of enzyme inhibition analysis.  For the purposes of SynergyScreen, we allow $m$ to take any real value.  A toxin might inhibit cell cutlure growth by various mechanisms, not necessarily involving an enzyme.  The curve modeled by equation (1) is sigmoid in shape.  This shape often seems to be more obvious when the $D$ axis is log-scaled.

By default, SynergyScreen fits Equation (1) directly to dose-response data using R function *nls*.  This type of model is referred to as *menls*, for "median effect [equation fit with] nls".

#### Linear regression
An alternative form of the median effect equation is
$$
\begin{align}
\frac{f_a}{f_u} = \left(\frac{D}{D_{50}}\right)^m
\end{align}
$$
where $f_a$ is fraction of the cells "affected" by the toxin, i.e. $f_a = (R_0-R)/R_0$ and $f_u$ is "fraction unaffected", i.e. $R/R_0$.

Equation (2) is linearizable by log transform:
$$
\begin{align}
\log\left(\frac{f_a}{f_u}\right) = -m \cdotp \log(D_{50}) + m \cdotp \log(D)
\end{align}
$$

Equation (3) is fit to dose-response data using by linear modeling using R function *lm*.  This type of model is referred to as *melm*, for "median effect [equation fit with] lm".

SynergyScreen uses *melm* to generate the initial guess required by *menls*.  In our experience, *menls* tends to produce better fits than *melm*.  However, *menls* occasionally fails to converge.

#### LOESS
SynergyScreen can also model dose-response data using local regression, as implemented in R function *loess*.  Control response value is added to the dataset modeled by LOESS and assigned a high weight (10 by default).

LOESS method is potentially more flexible than fitting the median effect equation, as it does not rely on any preconceptions about the shape of the dose-response curve.  However, LOESS can produce odd undulating curve shapes when given insufficient data, i.e. when there are too few distinct doses in the dataset.

### Quantifying synergy as Interaction Index

### Alternative approaches to synergy experiment modeling
Alternatives to single ray design include multiple rays and systematic exploration of the entire response surface.  However, these alternatives require more data and more complex modeling methodologies.  Our objective was to enable screening of compound collections for interactions.  Such screening requires a large number of synergy experiments, as the number of pairwise compound combinations is proportional to the square of the number of compounds in the screen.  Therefore, it is preferrable to use an approach that requires relatively few data points and uses simple and robust computational tools.  More complex methodologies suitable for modeling response surfaces and replicated single ray experiments have been published as R packages drc and mixlow **[insert refs]**.  An additional advantage of SynergyScreen is that it can generate experimental designs for 96-well plates. 